public static class ReadText
{
    public static string[] Scripts = {
        "Turn on this light",
        "Turn on that light",
        "Turn on this fan",
        "Turn on that fan",
        "Lock this door",
        "Unlock that door",
        "Turn on all of these lights",
        "Turn down my window",
        "Turn up my window",
        "Turn down that window",
        "Turn up that window",
        "This is the light",
        "The light is right here",
        "This is the fan",
        "The fan is right here",
        "This is the door",
        "The door is right here",
        "Move this seat forward",
        "Make the temperature cooler here",
        "Make the brightness higher in this area",
        "Where’s James’ office",
        "Where’s Monica’s office",
        "Where’s Men’s restroom",
        "Where’s women’s restroom",
        "Where’s Room 101",
        "Where’s the elevator",
        "Where’s the nearest staircase",
        "Show me the direction to James’ office",
        "Show me the direction to Monica’s office",
        "Show me the direction to Men’s restroom",
        "Show me the direction to women’s restroom",
        "Show me the direction to Room 101",
        "Show me the direction to the elevator",
        "Show me the direction to the nearest staircase",
        "Show me the direction to basement",
        "Show me the way out",
        "Where am I",
        "Next slide",
        "Previous slide",
        "Play this video",
        "Turn up the volume",
        "Switch to VGA cable",
        "Turn on the projector",
        "Turn off the projector",
        "Lower the projector screen",
        "Raise the projector screen",
        "Cooler water please",
        "Warmer water please",
        "Turn on the UV light",
        "Turn off the UV light",
        "I’m in the range",
        "I’m out of the range",
        "FaceTime Lisa",
        "Launch Photos",
        "Tell Susan I’ll be right there",
        "Message John I’ll be right back",
        "Apple pay 20 dollars to Susan",
        "Set up a meeting at 9",
        "What’s I love you in French?",
        "Did the Giants win?",
        "Find my trip to Italy trip last month",
        "Scan a QR code",
        "Give me direction home",
        "Table for four in Palo Alto",
        "Find political thrillers",
        "Play Norah Jones",
        "Remind me to call Mom",
        "Email Emily about the trip",
        "What’s the weather for today",
        "What is Apple’s stock price?",
        "Wake me up tomorrow at 7am",
        "What’s Emily’s address",
        "Note that I spent $12 on lunch",
        "Turn on Airplane mode",
        "Search the web for Polar Bears",
        "How many ounces are in a liter?",
        "Get Into Thin Air from Apple Books?",
        "Play podcasts",
        "Turn on the lights",
        "Show my passwords",
    };
}